### ISSUE TITLE
Damage/attack labels have stopped functioning properly since the latest update

### ISSUE THREAD

**Issue by TatianaKat** [RedReign/FoundryVTT-BetterRolls5e#126] opened 2020-10-11 10:44 UTC
Hi there,

I'm not sure if this is an issue only I'm having, but since I've updated my BetterRolls to the latest version, the labels are no longer working. They only display if shown 'below' the roll results, whereas before I had them displaying above without issues. The same goes for the 'attack' label as well. I've uploaded a screenshot to demonstrate what I mean. I thought this might have been a compatibility problem with Midi-QoL but it still occurs even with that module totally disabled.

[https://i.gyazo.com/939387c63329874be40e2362a9f0a1d1.png](url)

**Comment by RedReign** [comment] 2020-10-12 12:43
Hey, would you be able to provide a screenshot of your Better Rolls module settings? I tested most combination of options for the labels but perhaps I missed some.

**Comment by Stendarpaval** [comment] 2020-10-12 12:55
I'm running into the same issue, although I only started using Foundry VTT 3 days ago so I have not actually experienced the labels of Better Rolls working as intended. I have attached a screenshot that depicts most of the settings (I didn't change any) as well as the spell editor and the output, which lacks any labels or context output. I have currently turned off every other module except for Community Macros. I'm on version 0.6.6 of Foundry and version 1.1.11 of Better Rolls for 5e.

<img width="1440" alt="Screenshot 2020-10-12 at 14 50 54" src="https://user-images.githubusercontent.com/17188192/95748482-57a72200-0c9a-11eb-8d09-3829fed60e2d.png">

**Comment by RedReign** [comment] 2020-10-12 12:58
@Stendarpaval Unfortunately I've sorted out the root cause for labels not showing in 0.6.6, but I am only supporting 0.7.x Foundry from here on out.

**Comment by Stendarpaval** [comment] 2020-10-12 12:59
@RedReign I see, good to know. I'll look into updating to a supported version, then!

**Comment by RedReign** [comment] 2020-10-12 15:38
I have found the root cause.
dnd5e 0.97 Added some functionality that hides certain elements that use the `.flavor-text` selector. Attack roll labels in 0.6.6 use this. This can be fixed by reverting to dnd5e 0.96 **OR** updating Foundry to 0.7.3 and Better Rolls to the newest version.

**Closed by RedReign** 2020-10-12 15:38 UTC
