### ISSUE TITLE
Only Crit rolls are going to the chat

### ISSUE THREAD

**Issue by WomenlyProducts** [RedReign/FoundryVTT-BetterRolls5e#168] opened 2020-11-27 10:41 UTC
I have a few magical weapons and when I roll them it only goes to the chat with a roll if it's a critical hit. I've gone through and disabled pretty much every other module and it has to be better rolls. It was working fine 2 weeks ago

Also it works fine on all standard weapons from the SRD etc

**Comment by CarlosFdez** [comment] 2020-11-27 23:33
That's caused by a bug regarding the "Other" section. For now remove it until Red can make an update I think.

**Comment by CarlosFdez** [comment] 2020-12-22 00:03
Fixed in newer releases

**Closed by CarlosFdez** 2020-12-22 00:03 UTC
