### ISSUE TITLE
Line 272 of utils.js is throwing an error

### ISSUE THREAD

**Issue by Sky-Captain-13** [RedReign/FoundryVTT-BetterRolls5e#166] opened 2020-11-25 15:39 UTC
Adding data into the `Other Formula` field of an item (and maybe other places too) is causing utils.js to throw an error in chat. 

![image](https://user-images.githubusercontent.com/10356477/100248726-d33af680-2f09-11eb-8055-41cad7d958f3.png)

The rolls object is adding a null to the object that line 272 fails on. I was able to work around the issues by adding `if(roll != null)` in front of line 272, but the real solution would be to figure out where that null is coming from in `rolls`.

![image](https://user-images.githubusercontent.com/10356477/100249352-755ade80-2f0a-11eb-80a1-eea7e452f1cc.png)

**Comment by Sky-Captain-13** [comment] 2020-11-25 15:42
Ah, I am dumb. I should have just looked at line 1292 of `custom-roll.js`. Apparently the null is supposed to be a critRoll, but Other Formula isn't supposed to crit. At least, I don't want it to crit personally. I use it for extra damage and other options that should not be doubled or rolled again for critical hits.

`1292: this.dicePool.push(baseRoll, critRoll);`

**Comment by CarlosFdez** [comment] 2020-11-26 07:37
I was trying to figure out pf2e all day so I didn't notice this until just now.

Managed to reproduce, seems to happen if Other is a constant value. Its actually a bug I had fixed on another branch (the one you tested actually!) but forgot to backport to this one.

**Comment by Sky-Captain-13** [comment] 2020-11-26 13:06
Other Damage should not be rolling critical damage. If you create an Attack roll on an item and put dice in Other Damage, it does not have a Normal | Critical damage pop up when you click the button if you're using the core rolling method.

**Comment by CarlosFdez** [comment] 2020-11-26 20:33
Interesting. Yeah in BR in older versions it rolls crit like everything else, but in vanilla 5e it cannot roll crit. I think it depends on @RedReign then but I'm tempted on making it that way for consistency's sake.

**Comment by Sky-Captain-13** [comment] 2020-11-26 23:02
I believe Other Formula is intended to be used for attacks that have extra damage that is hidden behind a saving throw, like a Giant Spider bite. The poison damage should not double on a critical hit.

**Comment by RedReign** [comment] 2020-11-27 23:59
Heya, yes.
I've spoken with Carlos about this and I'm not super passionate about it one way or another. I'm okay with making Other formulae actually crit, but there seems to be some pushback on that, so perhaps they should function as they do in the vanilla system code and NOT crit.

That fix will be implemented with the crit upgrades that Carlos has been working on.

**Comment by CarlosFdez** [comment] 2020-12-23 00:10
And its been resolved. Ty for reporting.

**Closed by CarlosFdez** 2020-12-23 00:10 UTC
