### ISSUE TITLE
Support for resource consumption in D&D5e System Release v0.90

### ISSUE THREAD

**Issue by gazoir** [RedReign/FoundryVTT-BetterRolls5e#30] opened 2020-05-25 07:38 UTC
The latest update to the D&D5e system for Foundry supports class/item resource consumption. 

From the Gitlab for D&D5e System:
> Items can now define a consumed resource which is used when the item card is played or when an attack roll is made (in the case of ammunition). Consumed resources can be ammunition, materials, a character attribute, or the number of uses/charges allowed by another owned item. The relevant resource is automatically deducted when the item is used. This works great for tracking resource spenders that reference a common resource pool (like Sorcerer metamagic, Bardic Inspiration uses, Monk Ki points, or Fighter superiority dice). This also allows for ammo tracking with weapons which require physical ammunition, or strict tracking of spell components.
https://gitlab.com/foundrynet/dnd5e/-/releases/release-0.9.0

Support for this feature would be great for DMs who like to keep track of player resources.

**Comment by RedReign** [comment] 2020-05-29 00:44
Duplicate of #25

**Closed** 2020-05-29 00:45 UTC
Labels: duplicate
