### ISSUE TITLE
Some classes will not roll some spells

### ISSUE THREAD

**Issue by nhjjreuter** [RedReign/FoundryVTT-BetterRolls5e#128] opened 2020-10-12 14:04 UTC
Using version BetterRolls5e v1.1.13 on Foundry v0.7.3, spells sometimes fail to trigger a roll. In the one case this happened in my game, the spells that did not function were sleep, heroism, and healing words if the character casting the spell had the bard class. If I removed the class, or used this with another class (we tested rogue), the spell would work as intended.

When casting the sleep spell on a bard, the following message popped up in the console:

```
custom-roll.js:1336 Uncaught (in promise) ReferenceError: scaleInterval is not defined
    at CustomItemRoll.scaleDamage (custom-roll.js:1336)
    at CustomItemRoll.rollDamage (custom-roll.js:1239)
    at CustomItemRoll.fieldToTemplate (custom-roll.js:616)
    at custom-roll.js:691
```

**Comment by RedReign** [comment] 2020-10-12 14:30
Duplicate of #127 . Fixed in the next update.

**Closed by RedReign** 2020-10-12 14:30 UTC
Labels: duplicate
