### ISSUE TITLE
GM lost ability to use

### ISSUE THREAD

**Issue by gogone3** [RedReign/FoundryVTT-BetterRolls5e#226] opened 2021-02-28 05:19 UTC
All player actors work correctly, the gm and all npc sheets will not use better rolls, unless put into a macro.

**Comment by Moonshaft** [comment] 2021-02-28 18:06
I just logged in this afternoon to prep for my game later today and have encountered the same issue. When I log in as some players there are no problems and it works as intended, however when going back to my GM profile it's as if mod isn't active at all.

**Comment by CarlosFdez** [comment] 2021-02-28 23:14
I'll dig into this soon, is this with the default sheet or with something else?

**Comment by gogone3** [comment] 2021-02-28 23:17
Default sheet
Dnd5e.betternpcactor5esheet

**Comment by CarlosFdez** [comment] 2021-03-01 00:16
Working perfectly fine for me on the default sheet, attacking with basic attacks on an NPC sheet. Should probably look in the console and see what's wrong. Or give more details. If you updated to Foundry 0.8, its not currently supported (not even going to try to tackle that until 0.8.1 or 0.8.2).

**Comment by gogone3** [comment] 2021-03-01 02:01
im using 7.9, its only when using npc actors rolling from the character sheet. if I drag a skill to the macros and use it like a macro it works correctly.

**Comment by CarlosFdez** [comment] 2021-03-01 03:29
![image](https://user-images.githubusercontent.com/1286721/109448512-1da1a700-7a14-11eb-84ef-a7b22c96ac05.png)

Have you tried turning off all modules except Better Rolls to see if its due to an interaction? If I know what interaction causes it I can try to address it.

**Comment by CarlosFdez** [comment] 2021-03-01 03:58
Ah, I understand now. You weren't saying the bug was in both the default sheet *and* Better NPC Sheet, you were listing what was in the sheet dialog box. Yeah its not working in Better NPC Sheets. That sheet hasn't been updated in a while though nor does it use the new movement types from more recent 5e updates.

I'll look into fixing the integration but I really do recommend using a different sheet for NPCs like Tidy or something.

**Comment by CarlosFdez** [comment] 2021-03-01 05:59
After asking the Foundry League, not going to fix this. Better NPC sheet is 2 major (D&D) system versions behind, and will likely keep falling behind. I'd recommend moving to Tidy or Monster Blocks, or check if the D&DBeyond sheet is still up to date.

**Closed** 2021-03-01 05:59 UTC
