### ISSUE TITLE
Use with midi-qol causes private gm rolls to be public

### ISSUE THREAD

**Issue by SuicidalBomb** [RedReign/FoundryVTT-BetterRolls5e#218] opened 2021-02-13 10:45 UTC
I've tried disabling most of midis features except for the "check if attack hit" and "auto target with fireball, walls block targetting". Is there a possibility for this incompatibility being fixed or the aforementioned features being added?

**Comment by CarlosFdez** [comment] 2021-02-13 19:39
Can you show some pictures of what's going on?

Private GM rolls becoming public sounds like a midi side bug but I could still investigate.

**Comment by SuicidalBomb** [comment] 2021-02-14 04:07
![image](https://user-images.githubusercontent.com/78713526/107868189-2c069500-6e50-11eb-8712-57b165e41306.png)
Left is GM view with private GM roll selected and left is client view receiving the roll anyways. It is okay if this is unfixable, I will choose better rolls over Midi anyways. Thank you for your time.

**Comment by CarlosFdez** [comment] 2021-02-14 06:38
Asking because I need to be able to reproduce it. For example I can't see your chatbox so I don't know who is sending what, nor do I know your settings. I just tried a self/private role from the gm's side with both midi and br enabled and its completely hidden on the player side. Its either some combination of settings, or its another module interaction (like tabbed chatlog?)

Even if I can't fix it BR side, knowing it might help me send a report to the midi dev with more info.

**Comment by CarlosFdez** [comment] 2021-02-23 23:11
Closing since I can't address it without more info.

**Closed by CarlosFdez** 2021-02-23 23:11 UTC
