### ISSUE TITLE
Module not currently working with new beta

### ISSUE THREAD

**Issue by MerrickCat** [RedReign/FoundryVTT-BetterRolls5e#73] opened 2020-07-06 21:07 UTC
The module is not currently working with beta 0.6.5.

**Comment by JJBocanegra** [comment] 2020-07-07 15:57
I can confirm this, I was going crazy to see if another module could be interfering but I've done enough tests and I've come to the conclusion that it seems to be failing with the new version 0.6.5

**Comment by Rinzlers** [comment] 2020-07-07 16:56
Confirmed

**Comment by RedReign** [comment] 2020-07-07 19:53
Fixed in 1.1.8, thank you all for the report.

**Closed by RedReign** 2020-07-07 19:53 UTC
