### ISSUE TITLE
Request: Spell Support

### ISSUE THREAD

**Issue by N7Maddy** [RedReign/FoundryVTT-BetterRolls5e#64] opened 2020-06-26 12:11 UTC
Hi,

Would it be possible to get this to work on spells as well?
Specific example would be "Toll the Dead" where stand dice is 1d8, but 1d12 if target is already hurt.

\Maddy

**Comment by RedReign** [comment] 2020-06-26 16:16
Your request is very vague, but I assume your'e talking about "multi damage-type" scaling.
In which case, this is a duplicate of #55 .
Toll the Dead a very, very specific spell that works unlike any other official spell in 5e.
See [here](https://github.com/RedReign/FoundryVTT-BetterRolls5e/issues/55#issuecomment-648229744) for the solution.

**Closed by RedReign** 2020-06-26 16:16 UTC
Labels: duplicate
